packages:
  - "archive-static-sites/x-archive"
  - "archive-static-sites/facebook-archive"
  - "docs"

ignoredBuiltDependencies:
  - cypress
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias

onlyBuiltDependencies:
  - better-sqlite3
  - electron
