name: Release for Linux

on:
  push:
    tags:
      - "v*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make sure the version string matches the tag
        run: |
          CYD_VERSION=$(cat package.json | grep '"version"' | cut -d'"' -f4)
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          TAG_VERSION=${TAG_VERSION#v} # strip the leading 'v' from the tag
          if [ "$CYD_VERSION" != "$TAG_VERSION" ]; then
            echo "::error file=package.json,title=Version check failed::Version string in package.json $CYD_VERSION does not match the tag $TAG_VERSION"
            exit 1
          fi

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ matrix.arch }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.arch }}-

      - name: Install dependencies
        run: npm ci

      - name: Save Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ matrix.arch }}

      - name: Make release
        run: |
          CYD_VERSION=$(cat package.json | grep '"version"' | cut -d'"' -f4)
          if [[ "$CYD_VERSION" == *-dev ]]; then
            npm run make-dev-linux
          else
            npm run make-prod-linux
          fi

      - name: Upload DEB artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deb-packages-${{ matrix.arch }}
          path: out/make/deb/${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}/cyd_*.deb

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rpm-packages-${{ matrix.arch }}
          path: out/make/rpm/${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}/cyd-*.rpm

      - name: Upload ZIP artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zip-packages-${{ matrix.arch }}
          path: out/make/zip/linux/${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}/Cyd-*.zip
