name: Release for Linux

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make sure the version string matches the tag
        run: |
          CYD_VERSION=$(cat package.json | grep '"version"' | cut -d'"' -f4)
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          TAG_VERSION=${TAG_VERSION#v} # strip the leading 'v' from the tag
          if [ "$CYD_VERSION" != "$TAG_VERSION" ]; then
            echo "::error file=package.json,title=Version check failed::Version string in package.json $CYD_VERSION does not match the tag $TAG_VERSION"
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx create --use
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            docker buildx build --platform linux/arm64 -t my-arm64-builder --load .
          else
            docker buildx build --platform linux/amd64 -t my-amd64-builder --load .
          fi
      
      - name: Build Linux release in Docker container
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            docker run --rm -v $(pwd):/workspace -w /workspace my-arm64-builder ./scripts/make-linux-release.sh
          else
            docker run --rm -v $(pwd):/workspace -w /workspace my-amd64-builder ./scripts/make-linux-release.sh
          fi

      - name: Upload DEB artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deb-packages-${{ matrix.arch }}
          path: out/make/deb/${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}/cyd_*.deb

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rpm-packages-${{ matrix.arch }}
          path: out/make/rpm/${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}/cyd-*.rpm

      - name: Upload ZIP artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zip-packages-${{ matrix.arch }}
          path: out/make/zip/linux/${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}/Cyd-*.zip