name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      ELECTRON_CACHE: /tmp/.cache/electron
      ELECTRON_BUILDER_CACHE: /tmp/.cache/electron-builder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 xvfb

      - name: Install dependencies (skip postinstall)
        run: npm ci
        env:
          CI: true

      - name: Rebuild better-sqlite3 for Electron
        run: |
          ELECTRON_VERSION=$(node -e "console.log(require('./node_modules/electron/package.json').version)")
          echo "Rebuilding better-sqlite3 for Electron $ELECTRON_VERSION"
          npm_config_runtime=electron npm_config_target=$ELECTRON_VERSION npm_config_disturl=https://electronjs.org/headers npm_config_build_from_source=true npm rebuild better-sqlite3

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: xvfb-run -a npm run test:ci
        env:
          CI: true
