name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      ELECTRON_CACHE: /tmp/.cache/electron
      ELECTRON_BUILDER_CACHE: /tmp/.cache/electron-builder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Install @electron/rebuild
        run: pnpm add -D -w @electron/rebuild

      - name: Rebuild native modules for CI
        run: pnpm exec electron-rebuild --force

      - name: Run lint
        run: pnpm lint

      - name: Run tests (without rebuild)
        run: pnpm run test:ci

      - name: Run component tests
        run: pnpm test:components
